version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start --host 0.0.0.0 --port 12800
    ports:
      - "12800:12800"
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/